---
title : "Build a Quick Elo"
description : "Bad ELO"
author : "Robert Nguyen"
date : 2018-07-23
tags : ["ELO", "fitzRoy", "open science"]

---

One of my favourite sites is [squiggle](https://squiggle.com.au), mainly because I like to check out what other people have tipped, what their respective margins are and how they are aligned. 

As some of you know [James](https://twitter.com/plusSixOneblog) and I have been working on an AFL R package called [fitzRoy](https://github.com/jimmyday12/fitzRoy)

One of our main goals is to get more people to build out AFL models. 


For me that's mainly because I like reading AFL stats content, be it probably a bit too much!

Having done a presentation at [useR](https://user2018.r-project.org), one of the main problems I found with getting people wanting to give it a go is that they feel as though building their own model is simply too complex, that they are out of their depth. 

Well I am here to say, that's not true. Anyone can give it a go. 

I think there are many camps to the AFL stats fanbase. One of which I would like to try and include more. 

That is those who feel as though they can't contribute or can't analyse simply because they don't know R/How to build out models. 

So while you might be reading other blogs and sure they are "coding" it up from "scratch". I think a missing point to this thought is while that's true, it also doesn't have to be you. Lots of people develop packages and answer questions on sites like [stackoverflow](https://stackoverflow.com/questions/tagged/r).

So if you have ever wanted to build your own ELO for AFL why not use this [ELO package](https://cran.r-project.org/web/packages/elo/index.html). That's what it was designed for, for people to use it. 




```{r}
library(tidyverse)
library(elo)
library(fitzRoy)
library(lubridate)

results <- fitzRoy::get_match_results()
fixture <- fitzRoy::get_fixture(2019)

head(results)

results <- results %>%
  mutate(seas_rnd = paste0(Season, ".", Round.Number),
         First.Game = ifelse(Round.Number == 1, TRUE, FALSE))

head(results)

fixture <- fixture %>%
  filter(Date > max(results$Date)) %>%
  mutate(Date = ymd(format(Date, "%Y-%m-%d"))) %>%
  rename(Round.Number = Round)

# Set parameters
HGA <- 30 # home ground advantage
carryOver <- 0.5 # season carry over
k_val <- 20 # update weighting factor


map_margin_to_outcome <- function(margin, marg.max = 80, marg.min = -80){
  norm <- (margin - marg.min)/(marg.max - marg.min)
  norm %>% pmin(1) %>% pmax(0)
}

# Run ELO
elo.data <- elo.run(
  map_margin_to_outcome(Home.Points - Away.Points) ~
  adjust(Home.Team, HGA) +
    Away.Team +
    group(seas_rnd) +
    regress(First.Game, 1500, carryOver),
  k = k_val,
  data = results
)

as.data.frame(elo.data) %>% tail()

as.matrix(elo.data) %>% tail()

final.elos(elo.data)

fixture <- fixture %>%
  mutate(Prob = predict(elo.data, newdata = fixture))

head(fixture)



```

So if you run that script end to end you should have a working ELO model that you can play around with. 

# Somethings to note. 

* This model has no HGA, yes you read that right! `HGA <- 0` its set to 0 here!
* No mean reversion between seasons! `carryOver <- 1` I think thats right?
* I set k=20 for no reason other than I read this blog post here [538 ELO](https://fivethirtyeight.com/features/introducing-nfl-elo-ratings/), is that the best way to decide? What would you do differently?


