baseurl = "https://analysisofafl.netlify.com/"
title = "Analysis of AFL"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Robert Nguyen"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
math = true

[Author]
    name = "Robert Nguyen"
  #  profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Analysis of AFL"
    description = "Variance Semi- Explained"
    github = "https://github.com/anoafl/"
    #gitlab = "https://gitlab.com/XXX"
    #linkedin = "https://linkedin.com/in/XXX/"
    #gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/anoafl"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "analysisofafl@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
   # shareGooglePlus = true
    #shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2



[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
