---
title : "Regression to the Mean"
description : "An example using goalkicking"
author  : "Robert Nguyen"
date : 2018-06-20
tags : ["regression", "fitzRoy","modelling"]

---



<p>We also see this in sports, Hollinger refers to it as the <a href="http://www.espn.com/nba/columns/story?columnist=hollinger_john&amp;page=All-Decline-Team-081031">fluke rule</a>. Bill James calls it the <a href="http://grantland.com/the-triangle/fantasy-baseball-nerdy-keys-to-victory-the-plexiglas-principle/">plexiglas principle</a>, you might call it the <a href="https://en.wikipedia.org/wiki/Sports_Illustrated_cover_jinx">Sports Illustrated Jinx</a>. They all are different names from different people who have observed the same thing mean reversion or regression to the mean.</p>
<p>Regression to the mean as a concept was first introduced in 1886 by Galton who observed that on average taller parents have tall kids but not as tall as them. In otherwords their heights ‘shrunk’ towards the overall average at the time.</p>
<p>Regression to the mean is a powerful concept in statistics and how can we use it?</p>
<p>The following will be a simple goal-kicking example but if you wanted to, you could use something like supercoach scores (SC) to beat your friends or the bookie. Maybe you want to use it more at a <a href="https://www.foxsports.com.au/afl/worst-in-50-years-true-extent-of-afls-scoring-woes-revealed-after-one-of-lowestscoring-rounds-in-recent-history/news-story/d0cc1c3f86844aca7e25f6e5b155455e?nk=c85e2bf5aaa4e57ec96ed23c3a076d3c-1529480215">team level</a>? Will <a href="https://www.theage.com.au/sport/afl/afl-to-keep-close-watch-on-dip-in-scoring-20180503-p4zd9g.html">total scores return</a> via some regression to the mean?</p>
<div id="step-1-create-the-dataset" class="section level1">
<h1>Step 1 create the dataset</h1>
<p>Thankfully we can use <a href="https://github.com/jimmyday12/fitzRoy">fitzRoy</a> for the data we need pretty easily. Here we will take goals (G), behinds (B) and create a variable using <code>mutate</code> called <code>shots</code> which just represent total shots on goals (we don’t have access to kicks that were out on the full or dropped short) so this becomes the sum of goals and behinds.</p>
<p>We are looking at regression to the mean for goal kicking accuracy on a year to year bases on a player level. Hence our <code>group_by(Player, Team, Season)</code></p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages -------------------------------- tidyverse 1.2.1 --</code></pre>
<pre><code>## v ggplot2 2.2.1     v purrr   0.2.5
## v tibble  1.4.2     v dplyr   0.7.5
## v tidyr   0.8.1     v stringr 1.3.1
## v readr   1.1.1     v forcats 0.3.0</code></pre>
<pre><code>## -- Conflicts ----------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(fitzRoy)
data&lt;-fitzRoy::player_stats

data&lt;-data%&gt;%
  group_by(Player, Team, Season)%&gt;%
  summarise(TG=sum(G), TB=sum(B))




data%&gt;%
  group_by(Player,Team, Season)%&gt;%
  mutate(shots= TG + TB)%&gt;%
  ggplot(aes(x=shots))+geom_histogram(binwidth = 5)</code></pre>
<p><img src="/makemeauseR/2018-06-20-regression-to-the-mean_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code>data&lt;-data%&gt;%
  group_by(Player,Team, Season)%&gt;%
  mutate(shots= TG + TB)</code></pre>
</div>
<div id="step-two-subsetting-our-data-finding-ours-means" class="section level1">
<h1>Step Two Subsetting our data, finding ours means</h1>
<p>Looking at our earlier plot we see that we have lots of players who have failed to take a single shot at goal. We don’t want this to effect what we are doing down the track so lets arbitrary cut off shots at say 20 or more.</p>
<pre class="r"><code>subset = data$shots &gt; 19


good = data$TG[subset]
had_a_go = data$shots[subset]
names(good) = names(had_a_go) = paste(data$Player[subset], data$Season[subset], data$Team[subset])</code></pre>
<p>I know the above is tidyverse, but sometimes its nice to contrast it with base.</p>
<pre class="r"><code>indl_player_shot_pert = good/had_a_go

league_wide_pert = sum(good)/sum(had_a_go)
print(league_wide_pert)</code></pre>
<pre><code>## [1] 0.6009457</code></pre>
<pre class="r"><code>sigma2L = league_wide_pert*(1-league_wide_pert)/had_a_go

sigma2T = 0

for (i in 1:100000) {
  weight = 1/(2*(sigma2T + sigma2L)^2)
  sigma2T = sum(weight*((indl_player_shot_pert - league_wide_pert)^2 - sigma2L))/sum(weight)
}
print(sigma2T)</code></pre>
<pre><code>## [1] 0.001543792</code></pre>
<pre class="r"><code>sqrt(sigma2T)</code></pre>
<pre><code>## [1] 0.03929112</code></pre>
<pre class="r"><code>skill = (league_wide_pert/sigma2T + indl_player_shot_pert/sigma2L)/(1/sigma2T + 1/sigma2L)


head(sort(skill, decreasing = TRUE))</code></pre>
<pre><code>##          Luke Breust 2014 Hawthorn Tory Dickson 2015 Western Bulldogs 
##                          0.6701927                          0.6595703 
##   Christopher Mayne 2012 Fremantle   Drew Petrie 2012 North Melbourne 
##                          0.6573508                          0.6542362 
##   Barry Hall 2011 Western Bulldogs          Cyril Rioli 2016 Hawthorn 
##                          0.6525512                          0.6517646</code></pre>
<pre class="r"><code>tail(sort(skill, decreasing = TRUE))</code></pre>
<pre><code>##         Mitch Robinson 2011 Carlton         Dustin Martin 2013 Richmond 
##                           0.5546358                           0.5531560 
##        Daniel Jackson 2011 Richmond             Lewis Jetta 2010 Sydney 
##                           0.5503500                           0.5473482 
##         Jack Billings 2017 St Kilda Lindsay Thomas 2011 North Melbourne 
##                           0.5428329                           0.5385269</code></pre>
<pre class="r"><code>plot(indl_player_shot_pert, skill, xlim = c(.2, .5), col = &#39;orange&#39;)
abline(0, 1, col = &#39;blue&#39;)</code></pre>
<p><img src="/makemeauseR/2018-06-20-regression-to-the-mean_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>plot(density(indl_player_shot_pert), ylim = c(0, 30), col = &#39;orange&#39;,
     main = &#39;Distribution of Goal kicking skill in AFL&#39;,
     xlab = &#39;Goal Kicking  percentage&#39;)
lines(density(skill), col = &#39;blue&#39;)
legend(&#39;topright&#39;, c(&#39;True skill&#39;, &#39;Observed&#39;),
       col = c(&#39;blue&#39;, &#39;orange&#39;), lty = 1)</code></pre>
<p><img src="/makemeauseR/2018-06-20-regression-to-the-mean_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<p>How do we interpret these results?</p>
<p>You might first look at Luke Breust 2014 and it looks as though hes leading in accuracy you see the number below him <code>0.6701927</code> and are now thinking maybe that’s how many shots he converted. That is easy to check and we can do that using the script below.</p>
<pre class="r"><code>library(tidyverse)
library(fitzRoy)
data&lt;-fitzRoy::player_stats

data%&gt;%filter(Player==&quot;Luke Breust&quot; &amp; Season==2014)%&gt;%
  summarise(TG=sum(G), TB=sum(B))%&gt;%
  mutate(shotpert=TG/(TG+TB))</code></pre>
<pre><code>##   TG TB shotpert
## 1 57 12 0.826087</code></pre>
<p>We get <code>0.826087</code> which is not <code>0.6701927</code> so what is going on here?</p>
<p>Well our <code>0.6701927</code> is what we would call our luck adjusted percentage for Luke Breuest in 2014.</p>
<p>But what does this mean and how do we check it?</p>
<p>Our skill formula is as follow in R</p>
<pre class="r"><code>skill = (league_wide_pert/sigma2T + indl_player_shot_pert/sigma2L)/(1/sigma2T + 1/sigma2L)</code></pre>
<p>But what does this mean in english?</p>
<p>When we think about regression to the mean really we want to know these three things. * How good is the league or what is the population average * How good was the individual * After regressesing the indivual back what is left is their underlying true skill.</p>
<p>Lets look at the skill formula above, we have our</p>
<ul>
<li>league_wide_pert = 0.6009457 (League wide scoring shot percentage)</li>
<li>indl_player_shot_pert= 57/(57+12) (Luke Breust shot percentage for 2014)</li>
<li>sigma2T =0.001543792 (underlying true skill standard deviation of league)</li>
<li>sigma2L = 0.003475507 (underlying Luke Breust standard deviation for 2014) subbing all that into our skill formula above we get</li>
</ul>
<pre><code>((0.6009457/0.001543792) + (57/(57+12))/0.003475507 )/((1/0.001543792) + (1/0.003475507))</code></pre>
<p>Which just happens to be our skill for Luke Breust show earlier.</p>
<p>With an estimated 0.6701927 or 67.02% true skill for goal conversion, Luke Bruest is above average in true league average skill (0.6009457) and well outside one standard deviation of the population. His observed goal conversation percentage is 0.8261, which our estimate using regression to the mean is 0.6701927 which means he is kicking above his true talent level. It can be thought of as hes getting really lucky. Looking at his most recent completed year, he had a observed percentage of 0.66 (33/33+17) in other words as he aged and should have been getting better, he regressed towards his true mean which is still above league average. This year he is again below his best but still above league average.</p>
<pre class="r"><code> fitzRoy::player_stats%&gt;%
filter(Player==&quot;Luke Breust&quot; &amp;Season==2018)%&gt;%
  summarise(TG=sum(G),TB=sum(B)) %&gt;%
  mutate(accuracy=TG/(TG+TB))</code></pre>
<pre><code>##   TG TB  accuracy
## 1 25 11 0.6944444</code></pre>
<p>This shouldn’t surprise us, to put in perspective just how good Luke Breusts raw accuracy is lets create a table ranking players by accuracy over the years. Where not surprisingly he comes out as top of the list, while the mean accuracy of that group is 0.6369235. So it should be no surprise that Lukes accuracy was not sustainable</p>
<pre class="r"><code>fitzRoy::afldata%&gt;%
  select(First.name, Surname, Playing.for, Season, ID, Goals,Behinds)%&gt;%
  group_by(First.name, Surname, Playing.for, Season, ID)%&gt;%
  summarise(TG=sum(Goals),TB=sum(Behinds))%&gt;%
  mutate(accuracy=(TG/(TG+TB)))%&gt;%
  filter(TG&gt;49 &amp; Season&gt;1964)%&gt;%
  arrange(desc(accuracy)) </code></pre>
<pre><code>## # A tibble: 491 x 8
## # Groups:   First.name, Surname, Playing.for, Season [491]
##    First.name Surname    Playing.for     Season    ID    TG    TB accuracy
##    &lt;fct&gt;      &lt;fct&gt;      &lt;fct&gt;            &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;
##  1 Luke       Breust     Hawthorn          2014 11954    57    12    0.826
##  2 Stephen    Milne      St Kilda          2002   978    50    11    0.820
##  3 Tony       Lockett    St Kilda          1993   990    53    12    0.815
##  4 Tory       Dickson    Western Bulldo~   2015 12043    50    12    0.806
##  5 Matthew    Lloyd      Essendon          2008   336    62    16    0.795
##  6 Barry      Richardson Richmond          1971  2414    50    13    0.794
##  7 Tony       Lockett    St Kilda          1985   990    79    22    0.782
##  8 George     Young      St Kilda          1978  2299    70    21    0.769
##  9 Peter      Hudson     Hawthorn          1970  1822   146    44    0.768
## 10 Tony       Lockett    St Kilda          1989   990    78    24    0.765
## # ... with 481 more rows</code></pre>
</div>
