---
title : "Linear Regression an Introduction Through AFL"
description : "Learning linear regression with AFL examples"
author : "Robert Nguyen"
date : 2018-06-17
tags : ["regression", "p-values","fitzRoy","modelling"]

---



<p>Linear regression is an amazingly powerful concept in statistical modelling. It forms a major part of lots of first year statistics cources and how to deal with problems with linear regression can form second year units by themselves!</p>
<p>This post goal is to through the use of AFL data provide an intituitive guide to linear regression.</p>
<p>So why use AFL data?</p>
<p>With learning context and motivation are key. I think this is especially true with statistics. Hopefully you have found this blog through a combination of wanting to learn some stats, some R and an interest in footy.</p>
<div id="linear-regression" class="section level1">
<h1>Linear Regression</h1>
<p>Lets think about an example we know to be true. Lots of people do fantasy sports be it for fun with mates or having a punt. We know that <a href="https://fantasy.afl.com.au/help/index.html#/guidelines">AFL Fantasy</a> points are linear in nature. But lets pretend for a second that we didn’t know how points were allocated for fantasy.</p>
<p>We are interested in looking at whether the amount of kicks influences the fantsy points and if so by how much?</p>
</div>
<div id="step-one---get-the-data" class="section level1">
<h1>Step One - Get the data</h1>
<p>Our first step would be just to get the data and explore it.</p>
<p>Thankfully there exists an <a href="https://github.com/jimmyday12/fitzRoy">AFL R package</a> so we can go exploring.</p>
<pre class="r"><code>library(fitzRoy)
library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages -------------------------------- tidyverse 1.2.1 --</code></pre>
<pre><code>## v ggplot2 2.2.1     v purrr   0.2.5
## v tibble  1.4.2     v dplyr   0.7.5
## v tidyr   0.8.1     v stringr 1.3.0
## v readr   1.1.1     v forcats 0.3.0</code></pre>
<pre><code>## -- Conflicts ----------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>df&lt;-fitzRoy::player_stats</code></pre>
</div>
<div id="step-two---plot-the-data" class="section level1">
<h1>Step Two - Plot the data</h1>
<p>Step two, in practice I don’t think is done as often as it should be. We can learn lots of things from visually inspecting our data.</p>
<pre class="r"><code>df%&gt;%
  select(K,AF)%&gt;%
  ggplot(aes(x=K,y=AF))+geom_point()</code></pre>
<p><img src="/makemeauseR/2018-06-17-linear-regression-an-introduction-through-afl_files/figure-html/unnamed-chunk-2-1.png" width="672" /> Looking at this it would seem as though on average if a player has more kicks they will get more fantasy points. Intuitively the relationship looks fairly obvious, players who get more kicks get more fantasy points. BUT we might want a more precise estimate of the relationship between kicks and fantasy points. This is where our linear regression comes in handy dandy.</p>
</div>
<div id="step-three---the-linear-regression" class="section level1">
<h1>Step Three - The linear regression</h1>
<p>The way we have posed this problem is that AF (Fantasy scores) is a function of kicks. We would write this out to begin with as</p>
<p><code>AF ~ Kicks</code> This reads as AF (our dependant variable as it depends on Kicks) is a function of Kicks (our independant variable).</p>
<div id="all-models-are-wrong" class="section level3">
<h3>All models are wrong!</h3>
<p>George Box:</p>
<blockquote>
<p>All models are wrong but some are useful</p>
</blockquote>
<p>Models are by nature a simplifcation of reality, in this case we know that Kicks are not the only variable that has an effect on fantasy scores.</p>
<p>Another quote from George Box which is my personal favourite:</p>
<blockquote>
<p>Since all models are wrong the scientist cannot obtain a “correct” one by excessive elaboration. On the contrary following William of Occam he should seek an economical description of natural phenomena. Just as the ability to devise simple but evocative models is the signature of the great scientist so overelaboration and overparameterization is often the mark of mediocrity.</p>
</blockquote>
<p>So there you go, all models are wrong, we can’t take into account all the things that might effect our dependant variable. Think about team ratings (we will build a team rating linear regression later) how can you possible take into account all the factors that might affect how good a team is. There has and always will be some natural variable and some uncertainty around our estimates and isn’t that beautiful.</p>
<p>So now we now, that there will always be somethings that we can’t account for and things we could account for but don’t want to be it for model simplicity/interprebility, data issues or a host of other reasons. Hence we update our little equation above all these random and unaccounted for things <code>e</code> , and we write our new equation as <code>AF ~ Kicks + e</code> we can think of <code>e</code> as all the things that effect fantasy scores that are not kicks.</p>
</div>
</div>
<div id="get-me-my-coefficiants" class="section level1">
<h1>Get me my coefficiants</h1>
<pre class="r"><code>library(fitzRoy)
library(tidyverse)

df&lt;-fitzRoy::player_stats

eq1&lt;-lm(AF~K, data=df)
summary(eq1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = AF ~ K, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -63.610 -11.899  -1.803   9.827  91.553 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 26.81716    0.13880   193.2   &lt;2e-16 ***
## K            4.72596    0.01331   355.0   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 16.77 on 76074 degrees of freedom
## Multiple R-squared:  0.6235, Adjusted R-squared:  0.6235 
## F-statistic: 1.26e+05 on 1 and 76074 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>So what is going on here?</p>
<p>First, we load our packages that we need (fitzRoy, tidyverse). Then we get the player_stats data and call it df <code>df&lt;-fitzRoy::player_stats</code>. After that we fit our linear regression which we recall was <code>AF~K</code> we do this using the <code>lm</code> function in R and the dataset we use to fit the model is <code>df</code> from earlier.</p>
<p>Then we use <code>summary(eq1)</code> to see our output and coefficients.</p>
<p>Theres a lot going on there, so lets dig in and find what we are looking for.</p>
</div>
<div id="question-and-answers" class="section level1">
<h1>Question and Answers</h1>
<p>I am going to give something new a go here so I may even have to rewrite this blog post!</p>
<p><strong>You said earlier that a model can’t explain everything but it can explain somethings?</strong></p>
<p><em>That is true, a model is an abstraction away from reality, and there will always be some unexplained variation that we can’t or choose not to control for. A measure of the variation that our models explains is our </em> <code>Multiple R-squared</code> <em>for this example our</em> <code>Mutliple R-squared:</code>* is 0.6235 you can interpret this by saying that 62.35% of the variation in fantasy scores is accounted for by our model (in this case just kicks)*</p>
<p>In general you want your <span class="math inline">\(R^2\)</span> <code>Multple R-squared</code> to be higher rather than lower. The question of how high depends on what kind of data you are looking at. AFL modelling can be messy and noisy and affected by a whole heap of things outside of the model. But in this specific example because we know that fantasy scores are a direct function of the game statistics we would expect an <span class="math inline">\(R^2\)</span> as close to one as possible if we knew all the variables in the fantasy scores.</p>
<p><strong>What about this significance test and p-values that everyone is crazy for can you please tell me more</strong></p>
<p>That is a great question and you have really <a href="https://simplystatistics.org/2012/01/06/p-values-and-hypothesis-testing-get-a-bad-rap-but-we/">opened</a> <a href="http://www.amstat.org/asa/files/pdfs/P-ValueStatement.pdf">up</a> <a href="https://www.nature.com/news/statisticians-issue-warning-over-misuse-of-p-values-1.19503">a</a> <a href="http://www.fharrell.com/post/pval-litany/">can</a> <a href="http://fivethirtyeight.com/features/statisticians-found-one-thing-they-can-agree-on-its-time-to-stop-misusing-p-values/">of</a> <a href="http://www.stat.columbia.edu/~gelman/research/unpublished/p_hacking.pdf">worms</a>.</p>
<p><strong>Great so what is a the bloody thing!</strong></p>
<p>From the <a href="https://amstat.tandfonline.com/doi/abs/10.1080/00031305.2016.1154108#.Wyd4QKczZPY">ASA</a> statment on p-values</p>
<blockquote>
<p>Informally, a <em>p</em>-value is the probability under a specified statistical model that a statistical summary of the data (e.g., the sample mean difference between two compared groups) would be equal to or more extreme than its observed value.</p>
</blockquote>
<p>So the idea is, we start off with this idea of a <a href="https://www.ncbi.nlm.nih.gov/pubmed/23249368">null hypothesis</a> which in our example above for the coeffcient for kicks is that nothing is going on, that <span class="math inline">\(\beta_{1}\)</span> our coefficient for kicks is equal to 0. This <em>nothing going on here</em> is the same null hypothesis test for all the coefficents that lm would have produced estimates for if we added in more variables like handballs, marks, tackles etc.</p>
<p>So we have our null hypothesis, we assume nothings going on and then we calculate the probability of getting some test statistic as or more extreme to the one observed (4.726). So if nothing was going on here, the probability of getting the value of 4.726 for Kicks is small (&lt;2e-16). So, if the P-value is small, what you’re seeing is the probability of observing a test statistic as extreme as the one seen, is low if the null hypothesis were true (nothing is going on <span class="math inline">\(\beta_{1} = 0\)</span>)</p>
<div id="fantasy-scores-are-just-a-linear-model-right" class="section level3">
<h3>Fantasy scores are just a linear model right?</h3>
<p>Something that might be fun to do (well is fun to ) you can actually get how <a href="https://fantasy.afl.com.au/help/index.html#/guidelines">AF calculates the scores</a>. So why not knowing this put in those variables and you should get what the coefficients are right?</p>
<pre class="r"><code>library(fitzRoy)
library(tidyverse)

df&lt;-fitzRoy::player_stats

eq1&lt;-lm(AF~K +HB+M +T +FF +FA+HO +G +B, data=df)
summary(eq1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = AF ~ K + HB + M + T + FF + FA + HO + G + B, data = df)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -5.373e-10 -1.000e-13  0.000e+00  0.000e+00  3.921e-09 
## 
## Coefficients:
##               Estimate Std. Error    t value Pr(&gt;|t|)    
## (Intercept)  1.916e-11  1.547e-13  1.239e+02   &lt;2e-16 ***
## K            3.000e+00  1.488e-14  2.016e+14   &lt;2e-16 ***
## HB           2.000e+00  1.322e-14  1.513e+14   &lt;2e-16 ***
## M            3.000e+00  2.504e-14  1.198e+14   &lt;2e-16 ***
## T            4.000e+00  2.447e-14  1.635e+14   &lt;2e-16 ***
## FF           1.000e+00  5.546e-14  1.803e+13   &lt;2e-16 ***
## FA          -3.000e+00  5.399e-14 -5.557e+13   &lt;2e-16 ***
## HO           1.000e+00  8.293e-15  1.206e+14   &lt;2e-16 ***
## G            6.000e+00  5.625e-14  1.067e+14   &lt;2e-16 ***
## B            1.000e+00  7.440e-14  1.344e+13   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.438e-11 on 76066 degrees of freedom
## Multiple R-squared:      1,  Adjusted R-squared:      1 
## F-statistic: 3.053e+28 on 9 and 76066 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Yep there you go, the intercept is basically 0, Kicks are 3, handballs are 2, marks are 3, tackles are 4 etc. We can also see our <span class="math inline">\(R^2\)</span> is 1</p>
</div>
</div>
<div id="using-linear-regression-to-build-a-team-rating-system" class="section level1">
<h1>Using Linear regression to build a team rating system</h1>
<p>Before you get all angry and don’t <span class="citation">@me</span> here me out. Linear regression is a powerful tool and can even form part of a <a href="https://researchbank.rmit.edu.au/eserv/rmit:160744/Ryall.pdf">PhD thesis</a> in footy statistics. Its a great building block to build from just as more commonly used ELOS are another great building block and another post.</p>
<p>Using what we learnt above, we might want to formulate our regression so that we can predict the margin of win/loss for the home team.</p>
<p><span class="math inline">\(margin = Home.Score - Away.Score\)</span></p>
<p>Now we have margin as our outcome variable we want to try and predict what would be our actual predictors? Well we can’t use the actual Home.Score and Away.Score, thats just silly.</p>
<p>Lets write it out like:</p>
<p><span class="math inline">\(margin_{i} = home_quality_{i} - away_quality_{i} + \epsilon\)</span></p>
<p>Where for each game we have our home team, our away team and some measure of their quality.</p>
<pre class="r"><code>library(tidyverse)
library(fitzRoy)
matches&lt;-fitzRoy::get_match_results()
matches&lt;-matches%&gt;%filter(Season==2017)
teams&lt;-unique(matches$Home.Team)
all.teams &lt;- sort(unique(teams))
y &lt;- with(matches, Home.Points-Away.Points)

X0 &lt;- as_tibble(matrix(0,nrow(matches),length(all.teams)))
names(X0) &lt;- all.teams

for(mtrx in all.teams) {
  X0[[mtrx]] &lt;- 1*(matches$Home.Team==mtrx) - 1*(matches$Away.Team==mtrx)
}
X &lt;- X0[,names(X0) != &quot;Carlton&quot;]

linearmodel &lt;- lm(y ~ 0 + ., data=X)
head(coef(summary(linearmodel)))</code></pre>
<pre><code>##                   Estimate Std. Error    t value     Pr(&gt;|t|)
## Adelaide         48.061201   10.08678  4.7647734 3.747107e-06
## `Brisbane Lions` -9.127578   10.37399 -0.8798521 3.800509e-01
## Collingwood      19.240427   10.38167  1.8533074 6.538887e-02
## Essendon         20.508245   10.06377  2.0378301 4.295321e-02
## Footscray        15.920944   10.39112  1.5321677 1.271444e-01
## Fremantle        -4.472357   10.38228 -0.4307685 6.671250e-01</code></pre>
<pre class="r"><code>linearmodelratings&lt;-as.data.frame(coef(summary(linearmodel)))
linearmodelratings[with(linearmodelratings, order(-Estimate)), ]</code></pre>
<pre><code>##                    Estimate Std. Error    t value     Pr(&gt;|t|)
## Adelaide          48.061201  10.086776  4.7647734 3.747107e-06
## `Port Adelaide`   38.558691  10.293608  3.7458868 2.382649e-04
## Sydney            36.554207   9.972891  3.6653571 3.204001e-04
## Richmond          35.677314   9.902028  3.6030311 4.015994e-04
## GWS               32.594485  10.096762  3.2282115 1.467452e-03
## Geelong           31.789616  10.095630  3.1488492 1.903952e-03
## Melbourne         22.859720  10.171242  2.2474856 2.575873e-02
## `West Coast`      21.917010  10.210958  2.1464207 3.310749e-02
## Essendon          20.508245  10.063766  2.0378301 4.295321e-02
## Collingwood       19.240427  10.381671  1.8533074 6.538887e-02
## `St Kilda`        17.228341  10.373975  1.6607271 9.841758e-02
## Footscray         15.920944  10.391124  1.5321677 1.271444e-01
## Hawthorn          11.871564  10.381808  1.1434967 2.542711e-01
## `North Melbourne`  4.301616  10.382199  0.4143261 6.791027e-01
## Fremantle         -4.472357  10.382276 -0.4307685 6.671250e-01
## `Gold Coast`      -7.541466  10.172218 -0.7413788 4.593792e-01
## `Brisbane Lions`  -9.127578  10.373991 -0.8798521 3.800509e-01</code></pre>
</div>
