---
title: Making a one pager
author: Robert nguyen
date: '2019-01-09'
slug: making-a-one-pager
categories:
  - fitzRoy
  - R
tags:
  - betting
description: 'Maybe handy for fantasy'
---

Why might having a one pager be handy. 

* You might be really into fantasy sports so want to keep information like points given up by position handy.

Lets say you are playing a mate in your favourite fantasy league, having information like points given up by a team to a position tends to be handy. It's nothing new, in fact fantasy sports is big in the US and a site like [rotowire](https://www.rotowire.com/basketball/opp-avg.php) provides this information for fans quickly.

* You might like constructing your own ladders to like a [free kick count](https://twitter.com/triplemfooty/status/1011093422608867329) ladder.

Maybe you like to debate among your mates, maybe you work for a club and want to know where your team sits every week. 


* You might be a punter so having information like [Tony](https://twitter.com/matterofstats?lang=en) presents over in his [matterofstats](http://www.matterofstats.com/mafl-team-dashboards/matterofstats-2018-team-dashboard-for-round-23) might inform your betting strategy. 

No matter the purpose, information is key. But its more than just having the information available. You can construct a lot of the above but it would be very time consuming and probably a bit overwhelming. But that's why [James Day](https://twitter.com/jamesday87) and I have gotten [fitzRoy](https://github.com/jimmyday12/fitzRoy) together so all of these things are relatively quick, easy and can be updated weekly. 

